/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    ACard: typeof import('ant-design-vue/lib')['Card']
    ACheckbox: typeof import('ant-design-vue/lib')['Checkbox']
    ACol: typeof import('ant-design-vue/lib')['Col']
    AConfigProvider: typeof import('ant-design-vue/lib')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/lib')['DatePicker']
    ADivider: typeof import('ant-design-vue/lib')['Divider']
    AEmpty: typeof import('ant-design-vue/lib')['Empty']
    AForm: typeof import('ant-design-vue/lib')['Form']
    AFormItem: typeof import('ant-design-vue/lib')['FormItem']
    AImage: typeof import('ant-design-vue/lib')['Image']
    AInput: typeof import('ant-design-vue/lib')['Input']
    AInputNumber: typeof import('ant-design-vue/lib')['InputNumber']
    ALayout: typeof import('ant-design-vue/lib')['Layout']
    ALayoutContent: typeof import('ant-design-vue/lib')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/lib')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/lib')['LayoutSider']
    AList: typeof import('ant-design-vue/lib')['List']
    AMenu: typeof import('ant-design-vue/lib')['Menu']
    ARadio: typeof import('ant-design-vue/lib')['Radio']
    ARadioButton: typeof import('ant-design-vue/lib')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/lib')['RadioGroup']
    ARow: typeof import('ant-design-vue/lib')['Row']
    ASelect: typeof import('ant-design-vue/lib')['Select']
    ASpace: typeof import('ant-design-vue/lib')['Space']
    ASubMenu: typeof import('ant-design-vue/lib')['SubMenu']
    ATextarea: typeof import('ant-design-vue/lib')['Textarea']
    HighlightTextarea: typeof import('./src/components/HighlightTextarea.vue')['default']
    MarkDownRender: typeof import('./src/components/MarkDownRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('./src/components/base/TButton.vue')['default']
  }
}
